In [20]:
import numpy as ny  # Correctly using 'ny' for numpy alias

# Define the matrix A
A = ny.array([[1, 2, 3], 
              [0, 1, 0], 
              [2, 0, 1]])

print("Matrix A:")
print(A)

# Function to calculate the cofactor matrix
def cofactor(matrix):
    C = ny.zeros(matrix.shape)  # Correct assignment using '='
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            # Minor matrix: remove row i and column j
            minor = ny.delete(ny.delete(matrix, i, axis=0), j, axis=1)
            C[i, j] = (-1) ** (i + j) * ny.linalg.det(minor)
    return C

# Function to calculate the adjoint of a matrix
def adjoint(matrix):
    return cofactor(matrix).T  # Transpose of the cofactor matrix

# Calculating the adjoint of A
adj_A = adjoint(A)

print("Adjoint of A:")
print(adj_A)


Matrix A:
[[1 2 3]
 [0 1 0]
 [2 0 1]]
Adjoint of A:
[[ 1. -2. -3.]
 [-0. -5. -0.]
 [-2.  4.  1.]]


In [6]:
import numpy as ny
A=ny.array([[1,2,3],[0,1,0],[2,0,1]])
print("Matrix A :")
print(A)

def cofacter(matrix):
    c=ny.zeros(matrix.shape)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            minor=ny.delete(ny.delete(matrix,i,axis=0),j,axis=1)
            return c

def adjoint(matrix):
    return cofacter(matrix).T
print("After adjoint ")
adjoint_A=adjoint(A)
print(adjoint_A)

Matrix A :
[[1 2 3]
 [0 1 0]
 [2 0 1]]
After adjoint 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
